stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  preprocessing:
    cmd: python src\data_preprocessing.py
    deps:
    - data/raw
    - src\data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src\feature_engineering.py
    deps:
    - data/processed
    - src\feature_engineering.py
    outs:
    - data/featured
  model_building:
    cmd: src\model_buiding.py
    deps:
    - data/featured
    - src\model_buiding.py
    outs:
    - models\best_model.pkl
  evaluate_model:
    cmd: python src\evaluate_model.py
    deps:
    - models\best_model.pkl
    - src\evaluate_model.py
    metrics:
    - reports\metrics.json
